name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize]
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }} with ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            compiler: GCC
            install: sudo apt-get update && sudo apt-get install -y build-essential ninja-build clang-format-14
            build-mode: asan
          - os: macos-latest
            compiler: Clang
            install: "brew install ninja clang-format"
            build-mode: release
        #   - os: windows-latest
        #     compiler: MSVC
        #     install: "choco install ninja"
        #     build-mode: release

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC Dev Environment
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install dependencies
      run: ${{ matrix.install }}

    - name: Build 
      run: cmake --preset ${{ matrix.build-mode }} |
            cmake --build --preset ${{ matrix.build-mode }}

    - name: Check Format
      if: runner.os != 'Windows'
      run: cmake --build --preset ${{ matrix.build-mode }} --target check-format

    - name: Test
      run: ctest --preset ${{ matrix.build-mode }}
